In [1]:
import numpy as np 

graph = np.load('ni_graphs/spanish_qg_normalized.npy')

In [2]:
graph

array([[0.44526   , 0.07692367, 0.12117052, 0.02576991],
       [0.        , 0.68370986, 0.        , 0.45911205],
       [0.08830632, 0.04657436, 0.50009012, 0.07984545],
       [0.        , 0.36102529, 0.        , 0.45529002]])

In [16]:
columns = ['english QA', 'spanish QA', 'english QG', 'spanish QG']

# retrieve only the cells for spanish QA and spanish QG, do not include the english ones

spanish_qa = graph[:,1]
spanish_qg = graph[:,3]

# stack the two arrays vertically
spanish = np.vstack((spanish_qa, spanish_qg))

# retrieve only the rows for spanish QA and spanish QG
spanish_qa_only = spanish[:,1]
spanish_qg_only = spanish[:,3]

# stack the two arrays vertically
spanish = np.vstack((spanish_qa_only, spanish_qg_only))

In [18]:
spanish

# save to new array
np.save('ni_graphs/spanish_qa_qg_only.npy', spanish)

In [19]:
spanish

array([[0.68370986, 0.45911205],
       [0.36102529, 0.45529002]])

In [1]:
import numpy as np 

np.load('ni_graphs/spanish_qa_qg_normalized.npy')

array([[0. , 0. , 0. , 0. ],
       [0. , 0.5, 0. , 0.5],
       [0. , 0. , 0. , 0. ],
       [0. , 0.5, 0. , 0.5]])